language: bash
services: docker

env:
  - VERSION=7.1 VARIANT=apache_main
  - VERSION=7.1 VARIANT=apache_xhprof
  - VERSION=7.0 VARIANT=apache_main
  - VERSION=7.0 VARIANT=apache_xhprof
  - VERSION=5.6 VARIANT=apache_main
  - VERSION=5.6 VARIANT=apache_xhprof
  
before_script:
  - env | sort
  - cd "${VERSION}"
  - cd "${VARIANT}"
  - image="dropteam/drupal-php:test"

script:
  - travis_retry docker build -t "${image}"
  - docker run -d -p 127.0.0.1:80:80 --name test "${image}"
  - docker ps | grep -q test
